# Generated by Django 5.0.4 on 2024-04-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pancard',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Profile_img',
            field=models.ImageField(blank=True, default='static/profile_images/default_profile.jpg', null=True, upload_to='profile_images'),
        ),
    ]
